name: tuwu
description: Shoot them up
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: any
  cupertino_icons: ^1.0.2
  flame: ^1.8.2

dev_dependencies:
  flame_lint: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/tuwu/

